# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.

---
# vars file for bmc_fw_update

bmc_fw_update_task_failure: "Task failed with status: %s"
bmc_fw_update_version_failure: "Version returned from BMC doesn't match version in the file name"
bmc_fw_update_delegate: "{{ lookup('ansible.builtin.env', 'RUNON', default='localhost') }}"
bmc_fw_update_mandatory_msg: "username/password or auth_token is mandatory"
bmc_fw_update_mutual_exclusive_msg: "Only one authentication method is allowed. Provide either username/password or auth_token."
